version: '2'
services:
  lb:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - us
      - au
      - eu
    volumes:
      - ./acme-http01-webroot.lua:/etc/haproxy/acme-http01-webroot.lua
      - ./test/acme/.well-known/acme-challenge:/etc/haproxy/.well-known/acme-challenge
      - ./test/srv/maps/domain-to-tenant.map:/etc/auth0/cnamer/maps/domain-to-tenant.map
      - ./test/srv/maps/domain-to-backend.map:/etc/auth0/cnamer/maps/domain-to-backend.map
      - ./test/ssl:/etc/auth0/cnamer/ssl
  server:
    image: clue/json-server
    ports:
      - "8080:80"
    volumes:
      - ./test/srv/server/data.json:/data/db.json
  us:
    image: trinitronx/python-simplehttpserver
    volumes:
      - ./test/srv/us:/var/www:ro
  eu:
    image: trinitronx/python-simplehttpserver
    volumes:
      - ./test/srv/eu:/var/www:ro
  au:
    image: trinitronx/python-simplehttpserver
    volumes:
      - ./test/srv/au:/var/www:ro
