#!/usr/bin/env sh

export ENV=test
export CNAMER_MAP_FILE="./test/maps/domain-to-tenant.map"
export CNAMER_REGION_MAP_FILE="./test/maps/domain-to-backend.map"
export CNAMER_ENDPOINT=http://localhost:8080/db
export CNAMER_SSL_DIR="./test/ssl"
export TOKEN=deadbeef
export COMPOSE_FILE=docker-compose.test.yaml

dc() {
  docker-compose -f $COMPOSE_FILE $@
}

dc up -d server
python haproxy-cname-sync.py

dc down
dc rm server
